apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-shorten-tokens
policyDefaults:
  namespace: default
policies:
  - name: shorten-tokens
    manifests:
      - path: ../../../open-policy-agent/authentication-user-management/shorten-tokens/template.yaml
      - path: ../../../open-policy-agent/authentication-user-management/shorten-tokens/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}