apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-privileged-scc-usage
policyDefaults:
  namespace: default
policies:
  - name: disallow-privileged-scc-usage
    manifests:
      - path: template.yaml
      - path: constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}
