apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-image
  annotations:
    policies.kyverno.io/description: >-
      Check that an image is signed and verified against a public key.
      Unsigned images initiate a violation and fail to create.
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: verify-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELIRvjuiPMwpvoI+pVwzM+MKGedCW
          HiyhvASGNL+XLz+tmWQwRCVRFJhkGo+oVvNiRKVY9kEWW1R6NPfzyIQOBw==
          -----END PUBLIC KEY-----