apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snorunasanyscc
  annotations:
    description: Requires custom SCCs to not have the `RunAsAny` type for the `runAsUser` attribute.
spec:
  crd:
    spec:
      names:
        kind: K8sNoRunAsAnySCC
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snorunasanyscc

        violation[{"msg": msg}] {
          input.review.object.kind == "SecurityContextConstraints"
          not is_included(input.review.object.metadata.name, input.parameters.allowedSCCs)
          input.review.object.runAsUser.type == "RunAsAny"
          msg := sprintf("The SecurityContextConstraints object - %v has `runAsUser.type: RunAsAny` set. Change it to `MustRunAsRange` in order to comply with the rootless containers standard", [input.review.object.metadata.name])
        }

        is_included(scc_name, allowed_list) {
          scc_name == allowed_list[_]
        }