apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-external-ip-service
policyDefaults:
  namespace: default
policies:
  - name: disallow-external-ip-service
    manifests:
      - path: ../../../open-policy-agent/networking/external-ips/template.yaml
      - path: ../../../open-policy-agent/networking/external-ips/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}