apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-route-httpsonly
policyDefaults:
  namespace: default
policies:
  - name: route-httpsonly
    manifests:
      - path: ../../../open-policy-agent/networking/httpsonly/template.yaml
      - path: ../../../open-policy-agent/networking/httpsonly/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}