apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-anonymous
policyDefaults:
  namespace: default
policies:
  - name: disallow-anonymous
    manifests:
      - path: ../../../open-policy-agent/authentication-user-management/disallow-anonymous-users/template.yaml
      - path: ../../../open-policy-agent/authentication-user-management/disallow-anonymous-users/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}