apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sNamespaceRegulation
metadata:
  name: pod-namespace-regulation
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: 
      - default
      - kube-public
