apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snamespaceregulation
  annotations:
    description: Disallows pods that request to run in specific namespaces, the list of disallowed namespaces is configured in the constraint
spec:
  crd:
    spec:
      names:
        kind: k8sNamespaceRegulation
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snamespaceregulation

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          msg := sprintf("Pod '%v' can not be created in '%v' namespace", [input.review.object.metadata.name, input.review.object.metadata.namespace])
        }
