apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-policies
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhacm-policies
  namespace: rhacm-policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - rhacm-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: rhacm-policies
  namespace: rhacm-policies
spec:
  type: Git
  pathname: https://github.com/openshift-4-compliance/openshift-4-compliance-automation.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: redhat-acm
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rhacm-policies
  name: rhacm-policies-subscription
  namespace: rhacm-policies
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: rhacm-policies/rhacm-policies
  placement:
    placementRef:
      kind: PlacementRule
      name: rhacm-policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: rhacm-policies
  name: rhacm-policies-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"