apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-cluster-admin
policyDefaults:
  namespace: default
policies:
  - name: disallow-cluster-admin
    manifests:
      - path: ../../../open-policy-agent/authorization/disallow-cluster-admin/template.yaml
      - path: ../../../open-policy-agent/authorization/disallow-cluster-admin/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}