apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-emptydir
policyDefaults:
  namespace: default
policies:
  - name: disallow-emptydir
    manifests:
      - path: ../../../open-policy-agent/storage/disallow-emptydir/template.yaml
      - path: ../../../open-policy-agent/storage/disallow-emptydir/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}