apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./authorization/protect-default-scc/protect-default-scc.yaml
- ./authorization/host-namespaces/disallow-host-ports.yaml
- ./authorization/host-namespaces/disallow-host-network.yaml
- ./authorization/host-namespaces/disallow-host-pid.yaml
- ./authorization/host-namespaces/disallow-host-ipc.yaml
- ./networking/block-nodeport-services/block-nodeport-services.yaml
- ./networking/httpsonly/httpsonly.yaml
- ./resource-exhaustion/disallow-self-provisioner/disallow-self-provisioner.yaml
- ./trusted-image-sources/replace-image-registry/replace-image-registry.yaml
- ./trusted-image-sources/verify-signed-image/verify-signed-image.yaml
