apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-prevent-default-sa
policyDefaults:
  namespace: default
policies:
  - name: prevent-default-sa
    manifests:
      - path: ../../../open-policy-agent/authorization/prevent-default-serviceaccount-usage/template.yaml
      - path: ../../../open-policy-agent/authorization/prevent-default-serviceaccount-usage/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}