apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-self-provisioner
policyDefaults:
  namespace: default
policies:
  - name: disallow-self-provisioner
    manifests:
      - path: ../../../open-policy-agent/resource-exhaustion/disallow-self-provisioner/template.yaml
      - path: ../../../open-policy-agent/resource-exhaustion/disallow-self-provisioner/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}