apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-nodeport
policyDefaults:
  namespace: default
policies:
  - name: disallow-nodeport
    manifests:
      - path: ../../../open-policy-agent/networking/block-nodeport-services/template.yaml
      - path: ../../../open-policy-agent/networking/block-nodeport-services/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}