apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-sa-automounttoken
policyDefaults:
  namespace: default
policies:
  - name: sa-automounttoken
    manifests:
      - path: ../../../open-policy-agent/authorization/serviceaccount-automounttoken-prevention/template.yaml
      - path: ../../../open-policy-agent/authorization/serviceaccount-automounttoken-prevention/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}