apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-host-network
policyDefaults:
  namespace: default
policies:
  - name: disallow-host-network
    manifests:
      - path: ../../../open-policy-agent/authorization/disallow-host-network/template.yaml
      - path: ../../../open-policy-agent/authorization/disallow-host-network/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}