apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: ocphostnamespaces
  annotations:
    description: Controls usage of host namespaces.
spec:
  crd:
    spec:
      names:
        kind: OcpHostNamespaces
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package ocphostnamespaces
        violation[{"msg": msg, "details": {}}] {
            input_share_hostnamespace(input.review.object)
            msg := sprintf("Sharing the host namespace is not allowed: %v", [input.review.object.metadata.name])
        }
        input_share_hostnamespace(o) {
            o.spec.hostPID
        }
        input_share_hostnamespace(o) {
            o.spec.hostIPC
        }
        input_share_hostnamespace(o) {
            o.spec.hostNetwork
        }
        input_share_hostnamespace(o) {
            o.spec.allowHostPorts
        }
