apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-oauth-secured-identity
policyDefaults:
  namespace: default
policies:
  - name: oauth-secured-identity
    manifests:
      - path: ../../../open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/template.yaml
      - path: ../../../open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}