apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-scc-runasany
policyDefaults:
  namespace: default
policies:
  - name: disallow-scc-runasany
    manifests:
      - path: ../../../open-policy-agent/authorization/disallow-scc-runasany/template.yaml
      - path: ../../../open-policy-agent/authorization/disallow-scc-runasany/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}