apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallow-image-tags
policyDefaults:
  namespace: default
policies:
  - name: disallow-image-tags
    manifests:
      - path: ../../../open-policy-agent/trusted-image-sources/disallowedtags/template.yaml
      - path: ../../../open-policy-agent/trusted-image-sources/disallowedtags/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}