apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-pod-resource-limits
policyDefaults:
  namespace: default
policies:
  - name: pod-resource-limits
    manifests:
      - path: ../../../open-policy-agent/resource-exhaustion/pod-resource-limits/template.yaml
      - path: ../../../open-policy-agent/resource-exhaustion/pod-resource-limits/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}