apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowanonymous
  annotations:
    description: Disallows connections from anonymous users.
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowAnonymous
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisallowanonymous
        violation[{"msg": msg}] {
          review(input.review.object.subjects[_])
          msg := sprintf("Unauthenticated user reference is not allowed in %v %v ", [input.review.object.kind, input.review.object.metadata.name])
        }
        review(subject) = true {
          subject.name == "system:unauthenticated"
        }
        review(subject) = true {
          subject.name == "system:anonymous"
        }   