apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8soauthsecuredidentityprovidersonly
  annotations:
    description: 
spec:
  crd:
    spec:
      names:
        kind: K8sOAuthSecuredIdentityProvidersOnly
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package K8sOAuthSecuredIdentityProvidersOnly
        violation[{"msg": msg}] {
          input.review.kind.kind == "OAuth"
          input.review.object.metadata.name == "cluster"
          oauth := input.review.object 
    
          presentTypes := { type | type := oauth.spec.identityProviders[_].type}
          allowedTypes := { type | type := input.parameters.approvedProviders[_]}
    
          forbiddenTypes := allowedTypes - presentTypes
          count(forbiddenTypes) > 0 
    
          msg:= sprintf("You have at least %v unapproved identity provider types in your OAuth object. Make sure you only configure the following types: %v ",[count(forbiddenTypes),allowedTypes])
        }

